#!bin/bash
#

#Specify which shell to use
#$ -S /bin/bash

#Run on the current working folder
#$ -cwd

#Given this job a name
#$ -N somatic_1952

#Join standard output and error to a single file
#$ -j y

# Name the file where to redict standard output and error
#$ -o somatic_1952.qlog

# Project this job belongs to 
#$ -P SCNAseq

# Send an email when the job begins and when it ends running
#$ -m be

# Whom to send the email to
#$ -M yfu@bu.edu

# Now let's Keep track of some information just in case anything go wrong
echo "========================================"
echo "Starting on : $(date)"
echo "Running on node : $(hostname)"
echo "Current directory : $(pwd)"
echo "Current job ID : $JOB_ID"
echo "Current job name : $JOB_NAME"
echo "Task index number : $TASK_ID"
echo "========================================"

samtools mpileup -q 1 -f hg19.fa recal/1952C_recal_final.bam recal/1952_recal_final.bam | java -jar VarScan.v2.3.2.jar somatic --output 1952 --mpileup 1

echo "========================================"
echo "Finished on : $(date)"
echo "========================================"
